name: Lawandja
main: de.aestis.dndreloaded.Main
description: High Fantasy MMORPG WoW-like Framework for JenoMiners.de
version: 0.6.6
author: [Aestis.de, Jenominers.de]
api-version: 1.16
depend: [Citizens, InventoryMenuManager, GriefPrevention, WorldGuard, HolographicDisplays]
loadbefore: [Citizens, InventoryMenuManager, GriefPrevention]
loadafter: [WorldGuard]

commands:
   itemeditor:
      description: Opens ItemEditor
   setauctionator:
      description: Converts the currently selected NPC to an auctionator.
      usage: /setauctionator <category>
      aliases: [seta, sa]
      permission: lawc.auctions.admin

   dnd:
      description: Main Command for this Plugin
      
   questadmin:
      description: Reloads or saves QuestData.
      usage: /questadmin <reload/save>
      aliases: [qadmin, lwqa, qa]
      permission: lawc.quests.admin
      
   questedit:
      description: Directly edit Data from selected Quest.
      usage: /questedit <mode>
      aliases: [qedit, lwqe, qe]
      permission: lawc.quests.edit
   equestedit:
      description: Used to load or dump files for external Editor.
      usage: /questedit <dump|load>
      permission: lawc.quests.edit
      

   auctiondummy:
      description: Auction-Dummy command
      usage: /auctiondummy <sell/buy> <uuid>
      aliases: [acd]
      permission: lawc.auctions.use

      
   listquests:
      description: Lists all available Quests from the selected NPC.
      usage: /listquests
   selectquest:
      description: Selects a Quest by ID. Required before editing.
      usage: /selectquest <QuestID>
   questcreate:
      description: Creates a brand new Quest for the selected NPC.
      usage: /questcreate <Title>
   setquestrequired:
      description: Insert required Quest, if Player shouln't be allowed to access this Quest from the beginning.
      usage: /setquestrequired <QuestID>
   setquestfaction:
      description: Sets the Quests faction. (FREE, etc, etc)
      usage: /setquestfaction <Faction>
   setquestminreputation:
      description: Sets the Players reputation threshhold if needed.
      usage: /setquestminreputation <Value>
   setquesttitle:
      description: Use to edit the Quests Title/Name.
      usage: /setquesttitle <Title>
   setquesticon:
      description: Sets the Quests icon. Argument HAND takes the item you're currently holding in your mainhand.
      usage: /setquesticon <minecraft:item|HAND>
   setquestdescription:
      description: Sets the Quests main description.
      usage: /setquestdescription <Description>
   setquesttarget:
      description: Use if Quests target differs from the original Questgiver.
      usage: /setquesttarget
   setquestshort:
      description: Sets the shorter form of the Quests main description.
      usage: /setquestshort <Description>