package de.aestis.dndreloaded.Quests;

public enum QuestTypes {
	BLOCK_BREAK,
	BLOCK_BREAK_AREA,
	BLOCK_PLACE,
	BLOCK_PLACE_AREA,
	DELIVER_ITEM,
	KILL_MOBS,
	KILL_MOBS_AREA,
	INTERACT_ENTITY,
	REGION_ENTER
}
