Mysql:
  host: localhost
  database: quests
  port: 3306
  username: root
  password: rootpwd
  
# Testkommentar
  
Tasks:
  Sync:
    interval: 100
Items:
  Tools:
    Durability:
      enabled: true
      multiplier: 3
      Messages:
        cancelled: Â§eDas Ding ist kaputt!
    Sharpness:
      enabled: true
      chance: 3
Block:
  Drop:
    Wood:
      enabled: true
      usesilktouch: true
      Amount:
        min: 1
        max: 3
Localization:
  Professions:
    woodcutter: HolzfĂ¤ller
    blacksmith: Waffenschmied
    stonecutter: Steinmetz
    herbalist: KrĂ¤utersammler
    inscriber: Gelehrter
    alchemist: Alchemist
    farmer: Bauer
  Quests:
    Inventories:
      selector: Quest auswĂ¤hlen
