name: dndReloaded
main: de.aestis.dndreloaded.Main
description: Faction Based Minigame for JenoMiners.de
version: 0.9.43
author: Guerkchen385
api-version: 1.15
depend: [Citizens]
loadbefore: [Citizens]
commands:
   dnd:
      description: Main Command for this Plugin